# Generated by Django 2.2 on 2020-03-27 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200326_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Профиль'),
        ),
    ]
