# Generated by Django 2.2 on 2020-04-01 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200401_1033'),
        ('accounts', '0005_auto_20200328_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='webapp.Car', verbose_name='Марка авто'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='webapp.CarModel', verbose_name='Модель авто'),
        ),
    ]
