# Generated by Django 2.2 on 2020-04-09 06:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200401_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=20, verbose_name='Мобильный телефон')
        ),
        migrations.AlterField(
            model_name='profiles',
            name='type',
            field=models.CharField(choices=[('client', 'Клиент'), ('driver', 'Водитель')], max_length=20, verbose_name='Тип')
        ),
    ]
