# Generated by Django 2.2 on 2020-04-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200409_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='ban',
            field=models.BooleanField(default=False, verbose_name='Бан'),
        ),
    ]
