# Generated by Django 2.2 on 2020-03-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200327_1127'),
        ('webapp', '0006_auto_20200327_1511'),
    ]

    operations = [
    ]
