# Generated by Django 2.2 on 2020-03-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20200327_1544'),
        ('webapp', '0007_merge_20200327_1642'),
    ]

    operations = [
    ]
