# Generated by Django 2.2 on 2020-03-31 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0008_merge_20200328_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcements',
            name='clients',
        ),
        migrations.CreateModel(
            name='ClientsInAnnounce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seats', models.IntegerField(verbose_name='Количество мест')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='webapp.Announcements', verbose_name='обьявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
            ],
        ),
    ]
