# Generated by Django 2.2 on 2020-03-31 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0009_auto_20200331_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='clients',
            field=models.ManyToManyField(related_name='clients', through='webapp.ClientsInAnnounce', to=settings.AUTH_USER_MODEL, verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='clientsinannounce',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Announcements'),
        ),
        migrations.AlterField(
            model_name='clientsinannounce',
            name='seats',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientsinannounce',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
