# Generated by Django 2.2 on 2020-04-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20200331_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Марка авто')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Модель авто')),
            ],
        ),
    ]
