# Generated by Django 2.2 on 2020-04-01 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='model',
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель авто')),
                ('mark', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='webapp.Car', verbose_name='Марка авто')),
            ],
        ),
    ]
